### ISSUE TITLE
Add `ingress` and `egress` fields to the `system` resource for modeling data flows

### ISSUE THREAD

**Issue by ThomasLaPiana** [IABTechLab/fideslang#83]
### Is your feature request related to a specific problem?

We need a way to track directionality of data flowing between systems

### Describe the solution you'd like

Adding an `ingress` and an `egress` field to the `system` resources

### Describe alternatives you've considered, if any

More alternatives and discussion took place [here (internal only)](https://ethyca.atlassian.net/wiki/spaces/PM/pages/2409398307/Data+Flow+Modeling)

### Additional context

_Current Definition_: `yaml system: - fides_key: demo_analytics_system name: Demo Analytics System description: A system used for analyzing customer behaviour. system_type: Service privacy_declarations: - name: Analyze customer behaviour for improvements. data_categories: - user.contact - user.device.cookie_id data_use: improve.system data_subjects: - customer data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified dataset_references: # This goes away - demo_users_dataset `_Proposed Definition_`yaml system: - fides_key: demo_analytics_system name: Demo Analytics System description: A system used for analyzing customer behaviour. system_type: Service privacy_declarations: - name: Analyze customer behaviour for improvements. data_categories: - user.contact - user.device.cookie_id data_use: improve.system data_subjects: - customer data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified ingress: # This is added - fides_key: marketing_system type: system # An Enum of [system|dataset] action: process # An as-of-yet undefined Enum egress: # This is added - fides_key: customer_dataset type: dataset action: persist `

Note that the main changes here: 1. The removal of the `dataset_references` field 2. The addition of the `ingress` and `egress` fields

Design decisions to consider: 1. Ingress and Egress are defined on a per-declaration basis 2. This design does not let users specify which taxonomy types are involved in the egress/ingress, instead inheriting those values from the privacy declaration they are attached to 3. The enum values for `action` will need to be defined (process? persist? Read/write?) 4. No delineation between internal/external ingress/egress (external systems should be defined the same as internal systems, so this seems like an ok omission)

**Comment by ThomasLaPiana** [comment]
cc @PSalant726 @mfbrown @malaethyca @NevilleS

**Comment by PSalant726** [comment]
We'll need a way to define each `ingress` and `egress` as internal vs. external. A required boolean should suffice:
```yaml
system:
  ...
  ingress:
  - fides_key: marketing_system
    type: system
    action: process
    internal: false
  egress:
  - fides_key: customer_dataset
    type: dataset
    action: persist
    internal: true
```

Also, what is `action` meant to represent?

**Comment by ThomasLaPiana** [comment]
I guess `action` would be redundant with `data_use`?

Maybe the user would need a way to describe what that dataset or system is going to do with the data specifically.

Also according to a slack convo with @NevilleS it needs to include `volume`

**Comment by NevilleS** [comment]
I think this is a good compromise between our early design conversations but would like to push even further to try to get this to be as simple and self-documenting as possible. My feedback on this proposal is:
* pro: very simple to read, because there are only a few fields
* con: the "ingress/egress" language is probably confusing
* con: you need to use other systems & datasets to describe "what" data categories are flowing between systems, which is more complexity
* con: can't model flow from outside the map, e.g. sourced from users
* con: difficult to auto-generate these flows, since they belong to a privacy declaration

So I'd suggest maybe a few changes:
1. Use the name `data_flows` to list one-or-more flows for a given declaration. I think this is more likely to be understood by a new user as to what it means
2. Support three types of flows, to `system|dataset|user` (suggestions for "user" welcome... maybe "other" instead?)
3. Use the similar structure as a `DatasetReference` from fidesops (https://github.com/ethyca/fidesops/blob/main/src/fidesops/ops/schemas/dataset.py#L78) which already uses a `direction: to|from` concept, so that'd be more consistent across the language:
4. Allow Add a `data_categories` field, so you can provide a specific list of categories
5. Add a `meta` field where we track other things we might want to track and report on
```yaml
data_flows:
  - type: dataset
    fides_key: my_dataset
    direction: to
  - type: system
    fides_key: my_system
    direction: to
    data_categories: [user.name]
    meta:
      volume_bps: 3000
  - type: user
    direction: from 
    data_categories: [user.contact.email]
```

Putting that together:
```yaml
system:
  - fides_key: demo_analytics_system
    name: Demo Analytics System
    description: A system used for analyzing customer behaviour.
    system_type: Service
    privacy_declarations:
      - name: Analyze customer behaviour for improvements.
        data_categories:
          - user.contact
          - user.device.cookie_id
        data_use: improve.system
        data_subjects:
          - customer
        data_qualifier: aggregated.anonymized.unlinked_pseudonymized.pseudonymized.identified
     # Adding a new privacy declaration for clarity
     - name: Lead enrichment
        data_flows:
          - type: system
            fides_key: salesforce_system
            direction: to
            data_categories: [user.contact.email]
            meta:
              kbps: 3000
```

**Comment by NevilleS** [comment]
Separate conversation though, for @PSalant726: why would we have `internal` or `external` flows? It seems to me that a flow should be point-to-point, and the internal/external concept should be a property of the `System` instead?

**Comment by ThomasLaPiana** [comment]
@NevilleS you listed it as a con that they are part of a privacy declaration but then left that in in your design, just want to confirm that was intentional?

**Comment by NevilleS** [comment]
Yeah- I buy the argument that the wrapping of the `privacy_declaration` to provide meaning to the data flow is reasonable. But we do need to examine how we'd auto-generate placeholders/defaults for the declaration so that it can be part of an automated process.

I'm still not loving my "compromise" version, there's some good merit to the specificity of the `ingress`/`egress` pairings (based on @PSalant726's other comments, I think he'd want to require that you have both the src/dst systems declare each of their side of the flow?), and I also would prefer not to use `fides_key` as the field for the "other" system, but I think we're almost done here

**Comment by PSalant726** [comment]
> Separate conversation though, for @PSalant726: why would we have `internal` or `external` flows? It seems to me that a flow should be point-to-point, and the internal/external concept should be a property of the `System` instead?

The purpose is for data map reconciliation. In order to validate a map, we need to know if there _must_ be a system declaration for the source/destination of the data, or if there _should_ be. Having this property on the System declaration instead of the flow is perfectly fine.

In defense of simplicity, does the `data_flows` object _need_ the `type` parameter? Can't that be inferred from the `fides_key`?

Separately, I don't think the `kbps` property is worth including. The amount/volume/rate of data moving between systems will never be an exact, static number, so attempting to document it as such would lead to instantly stale manifests that would continuously contribute to the `git diff` each time they're validated.

**Comment by ThomasLaPiana** [comment]
1. As of today, they need to declare _all_ systems. This change would essentially tell users its ok not to declare systems, which is a choice we can make but is a distinct change in philosophy (i.e. before we clearly expected users to define third-party systems, hence system scanning in fidesctl)
2. Fides key is only unique per resource type, so actually a system and dataset could share a fides_key (bug or feature, you decide)
3. Agreed here

FWIW I also think `egress`/`ingress` is better, it is more specific and is already widely used in things like kubernetes as well as being the correct technical term. Keyword here being technical though, maybe this would confuse less-technical users

**Comment by ThomasLaPiana** [comment]
Outcome from a discussion call with @PSalant726 and @NevilleS 

* Add an `ingress` and `egress` field to the `system` object's top-level
* add `ingress` and `egress` fields to the `privacy_declaration` object

```yaml
system:
- fides_key: fidesctl_system
  ...
  privacy_declarations:
  - name: Collect sign-up data
    ...
    ingress: # Must exist on the system
    - fidesops
    egress: # Must exist on the system
    - fidescls

  ingress: # This is new
  - type: [system|dataset|user]
    fides_key: [user | fides_key]
    data_categories: [user.name, user.device.cookie_id]

  egress: # This is new
  - type: [system|dataset|user]
    fides_key: [user | fides_key]
    data_categories: [user.name, user.device.cookie_id]
```
